# Travis CI configuration file
# https://travis-ci.org/libexif/libexif-gtk

language: c

sudo: false

git:
  # Set to 10 instead of 1 to avoid problems when the most recent commits have [skip ci]
  depth: 10

# Install needed packages on Ubuntu & OS X
addons:
  apt:
    packages:
      - autopoint
      - libgtk2.0-dev
  homebrew:
    packages:
      - gtk+
    # The default OS X image is now (April 2020) too old to work without this
    update: true

env:
  # More configurations are configured in the matrix section
  matrix:
    - CONFIG=normal
    - CONFIG=c90
  global:
    - MAKEFLAGS='-j 2'

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  include:
  - env: CONFIG=clang6 DIST=xenial
    os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        packages:
          - autopoint
          - clang-6.0
          - libgtk2.0-dev
  - env: CONFIG=clang8 DIST=xenial
    os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-8
        packages:
          - autopoint
          - clang-8
          - libgtk2.0-dev
  - env: CONFIG=clang9 DIST=xenial
    os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        sources:
          sourceline:
            - deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main
          key_url:
            - https://apt.llvm.org/llvm-snapshot.gpg.key
        packages:
          - autopoint
          - clang-9
          - libgtk2.0-dev
  - env: CONFIG=clang10 DIST=xenial
    os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        sources:
          sourceline:
            - deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main
          key_url:
            - https://apt.llvm.org/llvm-snapshot.gpg.key
        packages:
          - autopoint
          - clang-10
          - libgtk2.0-dev
  - env: CONFIG=gcc8 DIST=xenial
    os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          sourceline:
            - ppa:ubuntu-toolchain-r/test
        packages:
          - autopoint
          - g++-8
          - libgtk2.0-dev
  - env: CONFIG=gcc9 DIST=xenial
    os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          sourceline:
            - ppa:ubuntu-toolchain-r/test
        packages:
          - autopoint
          - g++-9
          - libgtk2.0-dev
  - env: CONFIG=gtk3 DIST=xenial
    os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        packages:
          - autopoint
          - libgtk-3-dev
  - env: CONFIG=gtk3 DIST=xenial
    os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        packages:
          - autopoint
          - libgtk-3-dev
  - env: CONFIG=gtk3 DIST=bionic
    arch: arm64
    os: linux
    dist: bionic
    compiler: clang
    addons:
      apt:
        packages:
          - autopoint
          - gettext
          - libgtk-3-dev
  - env: CONFIG=gtk3 DIST=bionic
    arch: ppc64le
    os: linux
    dist: bionic
    compiler: clang
    addons:
      apt:
        packages:
          - autopoint
          - gettext
          - libgtk-3-dev
  - env: CONFIG=gtk3
    os: osx
    compiler: gcc
    addons:
      homebrew:
        packages:
          - gtk+3
        # The default OS X image is now (April 2020) too old to work without this
        update: true
  - env: CONFIG=gtk3
    os: osx
    compiler: clang
    addons:
      homebrew:
        packages:
          - gtk+3
        # The default OS X image is now (April 2020) too old to work without this
        update: true

before_install:
  # The apt addons section is ignored on bionic for some reason
  - if [ "$DIST" = "bionic" ] ; then sudo apt-get install -y autopoint libgtk-3-dev; fi

install:
  # Install the latest libexif
  - |
    # OS X has a weird alias that causes cd to abort with set -e so leave it
    # off over a cd.
    cd "$HOME"
    set -e
    git clone --depth=1 https://github.com/libexif/libexif.git
    set +e
    cd libexif
    set -e
    PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf
    set +e
    cd "$TRAVIS_BUILD_DIR"

script:
  # Ensure brew gettext is in the PATH so autopoint is found on OS X
  - PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf
  # Can't use -Werror because a bad interaction with configure disables NLS
  - if [ "$CONFIG" = "normal" ] ; then CFLAGS='-Wall -Wextra -O3'; fi
  - if [ "$CONFIG" = "c90" ] ; then CFLAGS='-std=iso9899:1990 -D_XOPEN_SOURCE=500 -Wall -Wextra -O3'; fi
  - if [ "$CONFIG" = "clang6" ] ; then CFLAGS='-Wall -Wextra -O3'; export CC=clang-6.0; fi
  - if [ "$CONFIG" = "clang8" ] ; then CFLAGS='-Wall -Wextra -O3'; export CC=clang-8; fi
  - if [ "$CONFIG" = "clang9" ] ; then CFLAGS='-Wall -Wextra -O3'; export CC=clang-9; fi
  - if [ "$CONFIG" = "clang10" ] ; then CFLAGS='-Wall -Wextra -O3'; export CC=clang-10; fi
  - if [ "$CONFIG" = "gcc8" ] ; then CFLAGS='-Wall -Wextra -O3'; export export CC=gcc-8; fi
  - if [ "$CONFIG" = "gcc9" ] ; then CFLAGS='-Wall -Wextra -O3'; export export CC=gcc-9; fi
  - if [ "$CONFIG" = "gtk3" ] ; then CFLAGS='-Wall -Wextra -O3'; CONFIGURE_OPTS='--with-gtk3'; fi

  - |
    cd "$HOME"/libexif
    set -e
    ./configure --prefix="${HOME}" CFLAGS="$CFLAGS" || { tail -300 config.log; false; }
    make V=1
    make V=1 install
    set +e
    cd "$TRAVIS_BUILD_DIR"

  # Finally, configure and build libexif-gtk
  - ./configure --prefix="${HOME}" CFLAGS="$CFLAGS" PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:${HOME}/lib/pkgconfig" $CONFIGURE_OPTS || { tail -300 config.log; false; }
  - make V=1
  # There are no automated tests to run
  - make V=1 install
